### ISSUE TITLE
Strawberry not playing mp3 files under macOS

### ISSUE THREAD

**Issue by dev4inno** [strawberrymusicplayer/strawberry-macos-dependencies#1]
Dear Jonas,

just a quick question: I am on MacOS Catalina and I like to use Strawberry.
I have installed the latest dmg (strawberry-1.0.7-x86_64.dmg) but I am getting this error message:

```
Your GStreamer installation is missing a plug-in.

../gst-plugins-base-1.20.3/gst/playback/gsturidecodebin.c(1028): no_more_pads_full (): /GstPlayBin:pipeline-6-pipeline/GstURIDecodeBin:uridecodebin5: no suitable plugins found: ../gst-plugins-base-1.20.3/gst/playback/gstdecodebin2.c(4702): gst_decode_bin_expose (): /GstPlayBin:pipeline-6-pipeline/GstURIDecodeBin:uridecodebin5/GstDecodeBin:decodebin7: no suitable plugins found: Missing decoder: MPEG-1 Layer 3 (MP3) (audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2, parsed=(boolean)true) 
```

However, I saw that you also released this file for MacOS: 

**strawberry-macos-catalina-dependencies.tar.xz**

Will this resolve the issue?
If yes, could you please advise how to install the Strawberry macOS Dependencies?

Thank you and kind regards,
Klaus

**Comment by jonaski** [comment]
This repository contains the dependencies for building strawberry from source, they are bundled in the dmg. It's not for support or bug reports. I'm not sure how you got here.

**Comment by dev4inno** [comment]
Thank you for your fast reply.
Sorry, my fault - I thought these were dependencies for the strawberry executable.
My Google search leads me to this place ...
So, unfortunately I cannot play mp3 songs with strawberry.
